import { ApplicationEmailContext, EmailMessage, EmailSender } from "./Email";

export interface InterviewReminderContext {
  recipient: string;
  candidateName: string;
  jobTitle: string;
  companyName: string;
  interviewDateText: string;
  interviewTimeText: string;
  timezone: string;
  meetingUrl?: string | null;
}

export class EmailNotificationService {
  constructor(private readonly sender: EmailSender) {}

  async applicationSubmitted(context: ApplicationEmailContext): Promise<void> {
    const message: EmailMessage = {
      to: context.recipient,
      subject: `Application submitted: ${context.jobTitle} at ${context.companyName}`,
      dedupeKey: `application-submitted:${context.applicationId}`,
      text: [
        `Hi ${context.candidateName},`,
        "",
        `Your application was submitted for ${context.jobTitle} at ${context.companyName}.`,
        `Application ID: ${context.applicationId}`,
        context.confirmationUrl ? `Confirmation: ${context.confirmationUrl}` : "",
        "",
        "This message was generated by your job-search automation system."
      ].filter(Boolean).join("\n")
    };

    await this.sender.send(message);
  }

  async applicationBlocked(context: ApplicationEmailContext): Promise<void> {
    const message: EmailMessage = {
      to: context.recipient,
      subject: `Manual review required: ${context.jobTitle} at ${context.companyName}`,
      dedupeKey: `application-blocked:${context.applicationId}`,
      text: [
        `Hi ${context.candidateName},`,
        "",
        `The automation did not submit your application for ${context.jobTitle} at ${context.companyName}.`,
        `Application ID: ${context.applicationId}`,
        context.reason ? `Reason: ${context.reason}` : "Reason: Manual review is required.",
        "",
        "No application was submitted automatically."
      ].filter(Boolean).join("\n")
    };

    await this.sender.send(message);
  }

  async interviewReminder(context: InterviewReminderContext): Promise<void> {
    const message: EmailMessage = {
      to: context.recipient,
      subject: `Interview reminder: ${context.jobTitle} at ${context.companyName}`,
      dedupeKey: `interview-reminder:${context.companyName}:${context.jobTitle}:${context.interviewDateText}:${context.interviewTimeText}`,
      text: [
        `Hi ${context.candidateName},`,
        "",
        `You have an interview for ${context.jobTitle} at ${context.companyName}.`,
        `Date: ${context.interviewDateText}`,
        `Time: ${context.interviewTimeText} (${context.timezone})`,
        context.meetingUrl ? `Meeting: ${context.meetingUrl}` : "",
        "",
        "This reminder was generated by your job-search automation system."
      ].filter(Boolean).join("\n")
    };

    await this.sender.send(message);
  }
}
