import { ApplicationEmailContext, EmailMessage, EmailSender } from "./Email";

export class EmailNotificationService {
  constructor(private readonly sender: EmailSender) {}

  async applicationSubmitted(context: ApplicationEmailContext): Promise<void> {
    const message: EmailMessage = {
      to: context.recipient,
      subject: `Application submitted: ${context.jobTitle} at ${context.companyName}`,
      dedupeKey: `application-submitted:${context.applicationId}`,
      text: [
        `Hi ${context.candidateName},`,
        "",
        `Your application was submitted for ${context.jobTitle} at ${context.companyName}.`,
        `Application ID: ${context.applicationId}`,
        context.confirmationUrl ? `Confirmation: ${context.confirmationUrl}` : "",
        "",
        "This message was generated by your job-search automation system."
      ].filter(Boolean).join("\n")
    };

    await this.sender.send(message);
  }

  async applicationBlocked(context: ApplicationEmailContext): Promise<void> {
    const message: EmailMessage = {
      to: context.recipient,
      subject: `Manual review required: ${context.jobTitle} at ${context.companyName}`,
      dedupeKey: `application-blocked:${context.applicationId}`,
      text: [
        `Hi ${context.candidateName},`,
        "",
        `The automation did not submit your application for ${context.jobTitle} at ${context.companyName}.`,
        `Application ID: ${context.applicationId}`,
        context.reason ? `Reason: ${context.reason}` : "Reason: Manual review is required.",
        "",
        "No application was submitted automatically."
      ].filter(Boolean).join("\n")
    };

    await this.sender.send(message);
  }
}
