import { SourceConfig } from "./SourceConfig";
import { JobSource } from "../../jobs/sources/JobSource";
import { LeverJobSource } from "../../jobs/sources/LeverJobSource";
import { GreenhouseJobSource } from "../../jobs/sources/GreenhouseJobSource";
import { AshbyJobSource } from "../../jobs/sources/AshbyJobSource";
import { RssJobSource } from "../../jobs/sources/RssJobSource";
import { RemoteOkJobSource } from "../../jobs/sources/RemoteOkJobSource";
import { PublicJsonJobSource } from "../../jobs/sources/PublicJsonJobSource";
import { FallbackJobSource } from "../../jobs/sources/FallbackJobSource";
import { StructuredDataJobSource } from "../../jobs/sources/StructuredDataJobSource";
import { FreePublicJobFeedBundleSource } from "../../jobs/sources/FreePublicJobFeedBundleSource";
import { PlatformSearchJobSource } from "../../jobs/sources/PlatformSearchJobSource";
import { TechmapJobSource } from "../../jobs/sources/TechmapJobSource";
import { AdzunaJobSource } from "../../jobs/sources/AdzunaJobSource";
import { JoobleJobSource } from "../../jobs/sources/JoobleJobSource";

export function createJobSource(config: SourceConfig): JobSource { switch(config.type){case "ats":return createAtsSource(config);case "rss":return createRssSource(config);case "api":return createApiSource(config);case "web":case "structured-data":return createStructuredDataSource(config);default:throw new Error(`No job-source adapter is registered for source type: ${config.type}`);} }
function createAtsSource(config:SourceConfig):JobSource{const adapter=config.name.toLowerCase();if(adapter==="lever"){if(!config.boardToken)throw new Error("Lever source requires boardToken");return new LeverJobSource(config.boardToken,undefined,config.companyDomain);}if(adapter==="greenhouse"){if(!config.boardToken)throw new Error("Greenhouse source requires boardToken");return new GreenhouseJobSource(config.boardToken,undefined,config.companyDomain);}if(adapter==="ashby"){if(!config.boardName)throw new Error("Ashby source requires boardName");return new AshbyJobSource(config.boardName,undefined,config.companyDomain);}throw new Error(`Unsupported ATS adapter: ${config.name}`);}
function createRssSource(config:SourceConfig):JobSource{if(!config.feedUrl)throw new Error(`RSS source requires feedUrl: ${config.name}`);return new RssJobSource({name:config.id,feedUrl:config.feedUrl,defaultCompanyName:config.name});}
function createApiSource(config:SourceConfig):JobSource{const adapter=config.name.toLowerCase();if(adapter==="remoteok")return new RemoteOkJobSource(config.feedUrl);if(adapter==="free-public-feeds")return new FreePublicJobFeedBundleSource();if(adapter==="platform-search")return new PlatformSearchJobSource();if(adapter==="himalayas"||adapter==="arbeitnow"){if(!config.feedUrl)throw new Error(`${adapter} source requires feedUrl`);const isUkFeed=adapter==="arbeitnow"&&config.feedUrl.toLowerCase().includes("arbeitnow.co.uk");return new PublicJsonJobSource(adapter,config.feedUrl,isUkFeed?"United Kingdom":null);}if(adapter==="jobicy"){if(!config.feedUrl)throw new Error("jobicy source requires feedUrl");return new FallbackJobSource(new PublicJsonJobSource(adapter,config.feedUrl),new RssJobSource({name:config.id,feedUrl:"https://jobicy.com/jobs/feed",defaultCompanyName:"Jobicy"}));}if(adapter==="techmap"){const apiKey=resolveApiKey(config);if(!apiKey)throw new Error(`Missing API key for source ${config.id}`);if(!config.apiUrl)throw new Error("techmap source requires apiUrl");return new TechmapJobSource({apiUrl:config.apiUrl,apiKey,portals:config.portals,countryCode:config.countryCode,city:config.city,workPlace:config.workPlace,title:config.title,skills:config.skills,dateCreated:config.dateCreated,page:1,limit:config.resultOnPage});}if(adapter==="adzuna"){const appId=process.env.ADZUNA_APP_ID?.trim();const appKey=process.env.ADZUNA_APP_KEY?.trim();if(!appId||!appKey)throw new Error("Adzuna requires ADZUNA_APP_ID and ADZUNA_APP_KEY");return new AdzunaJobSource({appId,appKey,countryCode:config.countryCode??"in",pages:config.pages??1,resultsPerPage:config.resultsPerPage??50,queries:config.queries,locations:config.locations});}if(adapter==="jooble"){const apiKey=resolveApiKey(config);if(!apiKey)throw new Error("Jooble requires apiKeyEnv and apiUrl");if(!config.apiUrl)throw new Error("jooble source requires apiUrl");return new JoobleJobSource({apiKey,apiBaseUrl:config.apiUrl,keywords:config.query??"React Frontend TypeScript Next.js",location:config.city??"Bengaluru, India",page:1,pages:config.pages??1,resultOnPage:config.resultOnPage});}throw new Error(`Unsupported API job source: ${config.name}`);}
function resolveApiKey(config:SourceConfig):string|null{return config.apiKeyEnv?process.env[config.apiKeyEnv]?.trim()||null:null;}
function createStructuredDataSource(config:SourceConfig):JobSource{if(!config.url)throw new Error(`${config.type} source requires url: ${config.name}`);return new StructuredDataJobSource({id:config.id,url:config.url,defaultCompanyName:config.name,companyDomain:config.companyDomain});}
