import { createHash } from "node:crypto";
import { AppError } from "../../shared/errors/AppError";
import { Job } from "../domain/Job";
import { JobSource } from "./JobSource";
import { JobDetailEnricher } from "./JobDetailEnricher";

type PublicJsonProvider = "himalayas" | "jobicy" | "arbeitnow";
export class PublicJsonJobSource implements JobSource {
 readonly name:string;
 constructor(private readonly provider:PublicJsonProvider,private readonly feedUrl:string,private readonly defaultCountry:string|null=null,private readonly detailEnricher:JobDetailEnricher|null=null){this.name=`${provider}:json`;}
 async fetchJobs(signal?:AbortSignal):Promise<Job[]>{
  const response=await fetch(this.feedUrl,{signal,headers:{accept:"application/json"}});
  if(!response.ok)throw new AppError(`${this.provider} request failed: ${response.status}`,{code:"JOB_SOURCE_REQUEST_FAILED",statusCode:response.status});
  const payload=(await response.json()) as unknown;
  const records=this.provider==="himalayas"?readHimalayas(payload):this.provider==="jobicy"?readJobicy(payload):readArbeitnow(payload);
  const jobs=records.map(record=>this.normalize(record));
  return this.detailEnricher ? this.detailEnricher.enrichJobs(jobs,signal) : jobs;
 }
 private normalize(record:NormalizedPublicJob):Job{const title=record.title.trim();const url=record.url.trim();const description=stripHtml(record.description);const companyName=record.companyName.trim()||"Unknown";const location=record.location?.trim()||"Worldwide";if(!record.id||!title||!url||!description)throw new AppError(`${this.provider} returned an incomplete job posting`,{code:"JOB_SOURCE_INVALID_DATA",statusCode:502});const contentHash=createHash("sha256").update([this.name,record.id,title,url,description].join("|")).digest("hex");return{source:this.name,sourceJobId:record.id,url,title,companyName,companyDomain:record.companyDomain??null,location,country:record.country??this.defaultCountry??inferCountry(location),workplaceType:record.workplaceType??"remote",employmentType:record.employmentType??null,description,postedAt:parseDate(record.postedAt),updatedAt:parseDate(record.updatedAt),contentHash};}
}
interface NormalizedPublicJob{id:string;title:string;url:string;companyName:string;companyDomain?:string|null;location?:string|null;country?:string|null;workplaceType?:"onsite"|"remote"|"hybrid"|null;employmentType?:string|null;description:string;postedAt?:string|number|null;updatedAt?:string|number|null;}
function readHimalayas(payload:unknown):NormalizedPublicJob[]{const jobs=objectArray(payload,"jobs");return jobs.flatMap(job=>{const item=job as Record<string,unknown>;const id=stringValue(item.guid);const title=stringValue(item.title);const url=stringValue(item.applicationLink);const rawDescription=stringValue(item.description)||stringValue(item.excerpt);
const experienceRequirement=[item.experience,item.experienceRequirement,item.minExperience,item.minimumExperience,item.yearsOfExperience].map(stringValue).find((value)=>/\b\d+(?:\.\d+)?\s*\+?\s*years?\b/i.test(value)) ?? "";
const description=experienceRequirement && /\b\d+(?:\.\d+)?\s*\+?\s*years?\b/i.test(experienceRequirement) ? `${rawDescription} Experience requirement: ${experienceRequirement}.` : rawDescription;
const countries=extractLocationRestrictions(item.locationRestrictions);const companyName=stringValue(item.companyName)||"Unknown";const companyDomain=extractCompanyDomain(description,companyName);return id&&title&&url&&description?[{id,title,url,companyName,companyDomain,location:countries.join(", ")||"Worldwide",country:countries.length===1?countries[0]:null,employmentType:stringValue(item.employmentType)||null,description,postedAt:item.pubDate as string|number|null,updatedAt:null}]:[];});}
function readJobicy(payload:unknown):NormalizedPublicJob[]{const jobs=objectArray(payload,"jobs");return jobs.flatMap(job=>{const item=job as Record<string,unknown>;const id=stringValue(item.id)||stringValue(item.jobSlug)||stringValue(item.url);const title=stringValue(item.jobTitle)||stringValue(item.title);const url=stringValue(item.url)||stringValue(item.jobUrl);const description=stringValue(item.jobDescription)||stringValue(item.description);const location=stringValue(item.jobGeo)||stringValue(item.location)||"Worldwide";const companyName=stringValue(item.companyName)||stringValue(item.company)||"Unknown";return id&&title&&url&&description?[{id,title,url,companyName,companyDomain:extractCompanyDomain(description,companyName),location,country:inferCountry(location),employmentType:stringValue(item.jobType)||stringValue(item.employmentType)||null,description,postedAt:item.pubDate as string|number|null,updatedAt:item.updatedAt as string|number|null}]:[];});}
function readArbeitnow(payload:unknown):NormalizedPublicJob[]{const jobs=objectArray(payload,"data");return jobs.flatMap(job=>{const item=job as Record<string,unknown>;const id=stringValue(item.slug)||stringValue(item.url);const title=stringValue(item.title);const url=stringValue(item.url);const description=stringValue(item.description);const location=stringValue(item.location)||"Worldwide";const remote=item.remote===true;const workplaceType=remote?"remote":"onsite";const companyName=stringValue(item.company_name)||"Unknown";return id&&title&&url&&description?[{id,title,url,companyName,companyDomain:extractCompanyDomain(description,companyName),location,country:inferCountry(location),workplaceType,employmentType:firstString(item.job_types),description,postedAt:item.created_at as string|number|null,updatedAt:null}]:[];});}
function extractLocationRestrictions(value:unknown):string[]{if(!Array.isArray(value))return[];return value.flatMap(item=>{if(typeof item==="string")return item.trim()? [item.trim()]:[];if(!item||typeof item!=="object")return[];const object=item as Record<string,unknown>;const candidate=[object.country,object.name,object.addressCountry,object.value].map(stringValue).find(Boolean);return candidate?[candidate]:[];});}
function extractCompanyDomain(description:string,companyName:string):string|null{const tokens=companyName.toLowerCase().split(/[^a-z0-9]+/).filter(token=>token.length>=3&&!['the','and','inc','ltd','llc','corp','company'].includes(token));if(!tokens.length)return null;for(const match of description.matchAll(/[A-Z0-9._%+-]+@([A-Z0-9.-]+\.[A-Z]{2,})/gi)){const rawHost=match[1];if(!rawHost)continue;const host=rawHost.toLowerCase().replace(/^www\./,'');const labels=host.split('.').filter(Boolean);if(labels.length<2)continue;const registrable=labels.slice(-2);const ccTld=new Set(['co','com','org','net','gov','ac']);if(tokens.some(token=>registrable.some(label=>label.includes(token))||(ccTld.has(labels[labels.length-2]??'')&&labels.slice(-3).some(label=>label.includes(token)))))return host;}return null;}
function firstString(value:unknown):string|null{if(Array.isArray(value)){const first=value.find((item):item is string=>typeof item==="string"&&item.trim().length>0);return first?.trim()??null;}return typeof value==="string"&&value.trim()?value.trim():null;}
function objectArray(payload:unknown,field:string):unknown[]{if(!payload||typeof payload!=="object")throw new AppError("Job source returned an unexpected payload",{code:"JOB_SOURCE_INVALID_DATA",statusCode:502});const value=(payload as Record<string,unknown>)[field];if(!Array.isArray(value))throw new AppError("Job source returned an unexpected jobs payload",{code:"JOB_SOURCE_INVALID_DATA",statusCode:502});return value.filter(item=>item&&typeof item==="object"&&!Array.isArray(item));}
function stringValue(value:unknown):string{return typeof value==="string"?value.trim():value===null||value===undefined?"":String(value).trim();}
function stripHtml(value:string):string{return value.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim();}
function parseDate(value?:string|number|null):Date|null{if(value===null||value===undefined||value==="")return null;const date=typeof value==="number"?new Date(value<10_000_000_000?value*1000:value):new Date(value);return Number.isNaN(date.getTime())?null:date;}
function inferCountry(location:string|null):string|null{if(!location)return null;const normalized=location.toLowerCase();if(/india|bangalore|bengaluru|mumbai|pune|hyderabad|chennai|delhi|gurugram|noida/.test(normalized))return"India";if(/singapore/.test(normalized))return"Singapore";if(/japan|tokyo|osaka|kyoto/.test(normalized))return"Japan";if(/united states|\busa\b|u\.s\.|america/.test(normalized))return"United States";if(/germany|berlin|munich|münchen|hamburg|frankfurt|cologne|köln/.test(normalized))return"Germany";if(/united kingdom|\buk\b|london|england|scotland|wales/.test(normalized))return"United Kingdom";return null;}
