import "dotenv/config";
import { promises as dns } from "node:dns";
import { spawn } from "node:child_process";
import path from "node:path";
import { Database } from "../src/database/Database";
import { ProactiveRecruiterRepository } from "../src/recruiters/ProactiveRecruiterRepository";
interface ContactRow { name?:string; email?:string; title?:string; company?:string; source_page?:string; source_file?:string; }
const EMAIL=/^[A-Za-z0-9.!#$%&'*+/=?^_{|}~-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$/;
const GENERIC=/^(noreply|no-reply|postmaster|webmaster|admin|support|privacy|legal|press|media|marketing|sales|security|billing|helpdesk)$/i;
const EXCLUDED=/^(octopus technologies|sketch brahma technologies)$/i;
function extract(files:string[]):Promise<ContactRow[]> { return new Promise((resolve,reject)=>{const child=spawn("python3",[path.resolve("scripts/extract-contact-resource.py"),...files],{stdio:["ignore","pipe","pipe"]});let out="",err="";child.stdout.on("data",d=>out+=d);child.stderr.on("data",d=>err+=d);child.on("error",reject);child.on("close",code=>{if(code!==0){reject(new Error(err.trim()||"extractor failed"));return;}const rows:ContactRow[]=[];for(const line of out.split("\n")){if(!line.trim())continue;try{const v=JSON.parse(line);if(!v._summary)rows.push(v as ContactRow);}catch{}}resolve(rows);});});}
async function mx(email:string):Promise<"LIKELY"|"UNVERIFIED"|"INVALID">{const d=email.split("@")[1]?.toLowerCase();if(!d)return"INVALID";try{return(await dns.resolveMx(d)).length?"LIKELY":"INVALID";}catch{return"UNVERIFIED";}}
function company(r:ContactRow):string{return r.company?.trim()||((r.email?.split("@")[1]??"").split(".")[0]??"Hiring Team").replace(/[-_]+/g," ");}
async function main(){const files=(process.env.PUBLIC_CONTACT_RESOURCE_PATHS??process.env.PUBLIC_CONTACT_RESOURCE_CSV_PATHS??"").split(/\s*,\s*/).map(x=>x.trim()).filter(Boolean);if(!files.length)throw new Error("Set PUBLIC_CONTACT_RESOURCE_PATHS to PDF/DOC/DOCX/XLS/XLSX/CSV/TXT/MD files.");const rows=await extract(files),db=new Database(process.env.DATABASE_URL??""),repo=new ProactiveRecruiterRepository(db);let persisted=0,invalid=0,excluded=0,likely=0,unverified=0;const seen=new Set<string>();try{for(const row of rows){const email=row.email?.trim().toLowerCase()??"";if(!EMAIL.test(email)||GENERIC.test(email.split("@")[0]??"")){invalid++;continue;}if(seen.has(email))continue;seen.add(email);const employer=company(row);if(EXCLUDED.test(employer)){excluded++;continue;}const status=await mx(email);if(status==="INVALID"){invalid++;continue;}if(status==="LIKELY")likely++;else unverified++;const domain=email.split("@")[1]??"";const candidate={contactType:"EMPLOYER" as const,recruiterName:row.name?.trim()||employer,recruiterRole:row.title?.trim()||"HR / Talent Acquisition",employer,employerDomain:domain,targetRoles:["Frontend Developer","React Developer","Next.js Developer","Software Engineer"],roleMatchScore:80,hiringEvidenceScore:80,overallConfidence:80,discoverySource:"public-web" as const,discoveryUrl:"file://"+(row.source_file??"contact-resource"),discoveryEvidence:[row.source_page??"","Imported contact resource: "+(row.source_file??""),"Public HR contact: "+email].filter(Boolean),evidenceType:"job_hiring_evidence" as const,evidenceDate:new Date().toISOString(),evidenceFreshness:"recent" as const,email,emailStatus:status,verificationEvidence:[{provider:"contact-resource-mx",status:status==="LIKELY"?"mx_present":"mx_unverified",confidence:status==="LIKELY"?80:40,mailboxLevel:false,source:row.source_file??"contact-resource"}]};if(await repo.persistCandidate(process.env.CANDIDATE_PROFILE_ID??"",candidate)){persisted++;}}console.log(JSON.stringify({status:"ok",feature:"MULTIFORMAT_CONTACT_RESOURCE",files:files.length,rowsExtracted:rows.length,uniqueEmails:seen.size,invalid,excluded,likely,unverified,persisted,mailboxVerificationClaimed:false},null,2));}finally{await db.close();}}
void main().catch(e=>{console.error(JSON.stringify({status:"FAILED",feature:"MULTIFORMAT_CONTACT_RESOURCE",error:e instanceof Error?e.message:String(e)},null,2));process.exitCode=1;});
