import { DeterministicJobMatcher } from "./DeterministicJobMatcher";
import { CandidateProfile } from "../candidates/CandidateProfile";
import { JobOpportunity } from "../jobs/domain/JobOpportunity";
const profile: CandidateProfile = { id:"candidate-1", yearsExperience:3, skills:["React","Next.js","TypeScript","Redux Toolkit","Node.js"], targetTitles:["Frontend Engineer","Frontend Developer"], location:"India", currentCompensationLpa:6.5 };
const NOW=new Date("2026-09-12T00:00:00.000Z"), matcher=new DeterministicJobMatcher({now:NOW});
function job(description:string,title="Frontend Developer",overrides:Partial<JobOpportunity>={}):JobOpportunity{return{id:"job-1",canonicalId:"canonical-1",canonicalUrl:"https://example.com/job-1",title,companyName:"Example",location:"Bengaluru",country:"India",workplaceType:"hybrid",employmentType:"full-time",description,postedAt:new Date("2026-09-08T00:00:00.000Z"),sourceUpdatedAt:null,lastSeenAt:NOW,closedAt:null,status:"ACTIVE",createdAt:NOW,updatedAt:NOW,...overrides};}
const evalJob=(description:string,title="Frontend Developer",overrides:Partial<JobOpportunity>={})=>matcher.evaluate(job(description,title,overrides),profile);

describe("DeterministicJobMatcher production calibration",()=>{
 it("APPLY: Bengaluru React frontend",()=>expect(evalJob("React, TypeScript and Next.js are required.").decision).toBe("APPLY"));
 it("APPLY: India React frontend",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Pune",country:"India"}).decision).toBe("APPLY"));
 it("APPLY: India remote React",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Remote - India",country:"India",workplaceType:"remote"}).decision).toBe("APPLY"));
 it("APPLY: explicitly India-eligible remote",()=>expect(evalJob("React and TypeScript. Remote in India.","Frontend Engineer",{location:"Remote",country:null,workplaceType:"remote"}).decision).toBe("APPLY"));
 it("REVIEW: worldwide remote with unclear India eligibility",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Worldwide",country:null,workplaceType:"remote"}).decision).toBe("REVIEW"));
 it("never APPLY: USA-only remote",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Remote - United States",country:"United States",workplaceType:"remote"}).decision).not.toBe("APPLY"));
 it("never APPLY: UK-only remote",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Remote - United Kingdom",country:"United Kingdom",workplaceType:"remote"}).decision).not.toBe("APPLY"));
 it("never APPLY: Berlin onsite React",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Berlin",country:"Germany",workplaceType:"onsite"}).decision).not.toBe("APPLY"));
 it("never APPLY: Paris hybrid React",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"Paris",country:"France",workplaceType:"hybrid"}).decision).not.toBe("APPLY"));
 it("never APPLY: UK onsite React",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{location:"London",country:"United Kingdom",workplaceType:"onsite"}).decision).not.toBe("APPLY"));
 it("APPLY: 2-4 years React",()=>expect(evalJob("React and TypeScript. 2 to 4 years of experience.").decision).toBe("APPLY"));
 it("APPLY: 3+ years React",()=>expect(evalJob("React and TypeScript. 3+ years of experience required.").decision).toBe("APPLY"));
 it("APPLY: Senior React requiring 3-4 years",()=>expect(evalJob("React and TypeScript. 3 to 4 years of experience.","Senior Frontend Engineer").decision).toBe("APPLY"));
 it("REVIEW: Senior React requiring 5+ years",()=>expect(evalJob("React and TypeScript. 5+ years of experience required.","Senior Frontend Engineer").decision).toBe("REVIEW"));
 it("never APPLY: 7+ years",()=>expect(evalJob("React and TypeScript. 7+ years of experience required.","Senior Frontend Engineer").decision).not.toBe("APPLY"));
 it("REJECT: Principal React",()=>expect(evalJob("React and TypeScript.","Principal Frontend Engineer").decision).toBe("REJECT"));
 it("REVIEW: Lead React",()=>expect(evalJob("React and TypeScript.","Lead Frontend Engineer").decision).toBe("REVIEW"));
 it("strongly matches React web",()=>expect(evalJob("Build customer-facing React and Next.js web interfaces.","Frontend Engineer").technicalOrientation).toBe("REACT_WEB"));
 it("REJECT: React Native primary is not React web",()=>expect(evalJob("Build mobile apps with React Native, Expo and Android/iOS.","Senior React Native Developer").decision).toBe("REJECT"));
 it("allows React web with optional React Native",()=>expect(evalJob("Build React and Next.js web applications. React Native is optional.","Frontend Engineer").decision).toBe("APPLY"));
 it("penalizes backend-heavy React/Node",()=>{const r=evalJob("Backend-focused role. Primarily backend Node.js, microservices, distributed systems and API architecture; React dashboard work is incidental.","Full Stack Engineer");expect(r.decision).not.toBe("APPLY");expect(r.technicalOrientation).toBe("BACKEND_FOCUSED");});
 it("scores frontend-heavy React/Node highly",()=>expect(evalJob("Build React and Next.js customer-facing web UI plus Node.js APIs.","Full Stack Engineer").decision).toBe("APPLY"));
 it("rejects clearly unrelated engineering",()=>expect(evalJob("Build Kubernetes infrastructure, Terraform and cloud networking.","Infrastructure Engineer").decision).toBe("REJECT"));
 it("rejects historical 2023 job",()=>expect(evalJob("React and TypeScript.","Software Engineer",{postedAt:new Date("2023-08-01T00:00:00.000Z")}).decision).toBe("REJECT"));
 it("gives recent jobs a freshness advantage",()=>{const recent=evalJob("React and TypeScript.","Frontend Engineer",{postedAt:new Date("2026-09-10T00:00:00.000Z")});const old=evalJob("React and TypeScript.","Frontend Engineer",{postedAt:new Date("2026-06-01T00:00:00.000Z")});expect(recent.matchScore).toBeGreaterThan(old.matchScore);});
 it("does not reject missing salary",()=>expect(evalJob("React and TypeScript.","Frontend Engineer").decision).toBe("APPLY"));
 it("penalizes clearly incompatible salary",()=>expect(evalJob("React and TypeScript. Salary ₹3-4 LPA.","Frontend Engineer").matchScore).toBeLessThan(60));
 it("REJECT: Octopus Technologies",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{companyName:"Octopus Technologies"}).decision).toBe("REJECT"));
 it("REJECT: Sketch Brahma Technologies",()=>expect(evalJob("React and TypeScript.","Frontend Engineer",{companyName:"Sketch Brahma Technologies"}).decision).toBe("REJECT"));
 it("rejects keyword-heavy wrong role",()=>expect(evalJob("Marketing role. React, Next.js, TypeScript, Node.js, Redux and GraphQL are keywords in the product.","Product Marketing Manager").decision).toBe("REJECT"));
 it("rejects keyword-heavy wrong geography",()=>expect(evalJob("React, Next.js, TypeScript, Node.js, Redux and GraphQL.","Frontend Engineer",{location:"San Francisco",country:"United States",workplaceType:"onsite"}).decision).not.toBe("APPLY"));
 it("rejects keyword-heavy incompatible seniority",()=>expect(evalJob("React, Next.js, TypeScript, Node.js, Redux and GraphQL. 10+ years required.","Principal Frontend Engineer").decision).toBe("REJECT"));
 it("preserves deterministic duplicate input behavior",()=>expect(evalJob("React and TypeScript.")).toEqual(evalJob("React and TypeScript.")));
});
