import { RecruiterIdentityRepository } from "./RecruiterIdentityRepository";
import { RecruiterIdentityCandidate } from "./RecruiterDiscovery";
function storedRow(){return{id:"contact-1",company_name:"Example Corp",company_domain:"example.com",email:"careers@example.com",full_name:null,title:"Recruiting contact",department:"recruiting",seniority:null,country:null,location:null,confidence:100,verified:false,verification_status:"unverified_public_source",provider:"public-web",linkedin_profile_url:null,email_discovery_status:"FOUND",email_status:"UNVERIFIED",domain_status:"VALID",mx_status:"UNKNOWN",mailbox_evidence:false,verification_evidence:[],discovery_source:"public-web",suppressed:false,suppression_reason:null,last_contacted_at:null,email_discovery_attempted_at:null,updated_at:new Date()};}
const candidate:RecruiterIdentityCandidate={email:"careers@example.com",title:"Recruiting contact",department:"recruiting",confidence:100,verified:false,verificationStatus:"unverified_public_source",provider:"public-web",sources:[{type:"job_posting",confidence:100}]};
function updateCall(database:any):any[]{return database.query.mock.calls.find((call:any[])=>typeof call[0]==="string"&&call[0].includes("UPDATE recruiter_contacts"))??[];}
describe("RecruiterIdentityRepository",()=>{
 it("uses an atomic typed identity-key upsert instead of an ambiguous nullable-parameter conflict lookup",async()=>{const row=storedRow();const database={query:jest.fn().mockResolvedValue({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);const first=await repository.upsertIdentity("Example Corp","example.com",candidate);const second=await repository.upsertIdentity("Example Corp","example.com",candidate);expect(first.id).toBe("contact-1");expect(second.id).toBe("contact-1");expect(database.query).toHaveBeenCalledTimes(2);const sql=database.query.mock.calls[0]?.[0] as string;expect(sql).toContain("ON CONFLICT (company_domain, identity_key) WHERE identity_key IS NOT NULL DO UPDATE SET");expect(sql).toContain("RETURNING id,company_name,company_domain");expect(sql).not.toContain("LOWER($2::text)");});
 it("does not reuse the email parameter inside CONCAT during enrichment, avoiding a varchar/text parameter type conflict",async()=>{const row=storedRow();const database={query:jest.fn().mockResolvedValueOnce({rows:[{company_domain:"example.com",email:"careers@example.com"}]}).mockResolvedValueOnce({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);await repository.enrichEmail("contact-1","careers@example.com",false,"UNVERIFIED",90);const sql=updateCall(database)[0] as string;expect(sql).toContain("CONCAT('email:',email)");expect(sql).not.toContain("CONCAT('email:',$2");});
 it("does not promote verified=true plus MX-only evidence into mailbox verification",async()=>{const row={...storedRow(),verification_status:"domain_mx_verified",email_status:"LIKELY",mx_status:"EXISTS"};const database={query:jest.fn().mockResolvedValueOnce({rows:[{company_domain:"example.com",email:"careers@example.com"}]}).mockResolvedValueOnce({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);const result=await repository.enrichEmail("contact-1","careers@example.com",true,"domain_mx_verified",96);expect(result?.verified).toBe(false);const params=updateCall(database)[1] as unknown[];expect(params?.[2]).toBe(false);expect(params?.[3]).toBe("domain_mx_verified");expect(params?.[4]).toBe("LIKELY");expect(params?.[7]).toBe(false);});
 it("does not promote non-mailbox evidence even when the status is mailbox_verified",async()=>{const row={...storedRow(),verification_status:"mailbox_verified",email_status:"UNVERIFIED"};const database={query:jest.fn().mockResolvedValueOnce({rows:[{company_domain:"example.com",email:"careers@example.com"}]}).mockResolvedValueOnce({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);const result=await repository.enrichEmail("contact-1","careers@example.com",true,"mailbox_verified",99,[{provider:"public-web",status:"VERIFIED",mailboxLevel:false,source:"public-search"}]);expect(result?.verified).toBe(false);const params=updateCall(database)[1] as unknown[];expect(params?.[2]).toBe(false);expect(params?.[3]).toBe("UNVERIFIED");expect(params?.[4]).toBe("UNVERIFIED");});
 it("accepts only explicit mailbox-level evidence for mailbox verification",async()=>{const row={...storedRow(),verified:true,verification_status:"mailbox_verified",email_status:"VERIFIED",mailbox_evidence:true,verification_evidence:[{provider:"snov",status:"mailbox_verified",mailboxLevel:true,source:"snov_email_verification"}]};const database={query:jest.fn().mockResolvedValueOnce({rows:[{company_domain:"example.com",email:"careers@example.com"}]}).mockResolvedValueOnce({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);const result=await repository.enrichEmail("contact-1","careers@example.com",true,"mailbox_verified",99,[{provider:"snov",status:"mailbox_verified",mailboxLevel:true,source:"snov_email_verification"}]);expect(result?.verified).toBe(true);const params=updateCall(database)[1] as unknown[];expect(params?.[2]).toBe(true);expect(params?.[3]).toBe("mailbox_verified");expect(params?.[4]).toBe("VERIFIED");expect(params?.[7]).toBe(true);});
 it("blocks a mailbox verification result when the discovered email domain does not match the company domain",async()=>{const row={...storedRow(),email:"person@other.example",domain_status:"INVALID",verified:false,mailbox_evidence:false,email_status:"INVALID",verification_status:"INVALID"};const database={query:jest.fn().mockResolvedValueOnce({rows:[{company_domain:"example.com",email:"careers@example.com"}]}).mockResolvedValueOnce({rows:[row]})};const repository=new RecruiterIdentityRepository(database as never);const result=await repository.enrichEmail("contact-1","person@other.example",true,"mailbox_verified",100,[{provider:"snov",status:"valid",mailboxLevel:true,source:"snov_email_verification"}]);expect(result?.verified).toBe(false);const params=updateCall(database)[1] as unknown[];expect(params?.[2]).toBe(false);expect(params?.[3]).toBe("INVALID");expect(params?.[4]).toBe("INVALID");expect(params?.[5]).toBe("INVALID");});
});
